import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/app/globals.css';
import Header from '@/components/layout/Header';
import NextAuthWrapper from '@/lib/next.auth.wrapper';
import { auth } from '@/auth';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Craft Market 3D',
  description: 'Generated by create next app',
  icons: ['logo.svg'],
};

const UserSessionWrapper = async ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const session = await auth();

  const user = session?.user;

  return (
    <>
      <Header user={user} />
      {children}
    </>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} min-h-[125vh] antialiased`}>
        <NextAuthWrapper>
          <UserSessionWrapper>{children}</UserSessionWrapper>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
