import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/app/globals.css';
import NextAuthWrapper from '@/lib/next.auth.wrapper';
import CartProvider from '@/context/CartProvider';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Craft Market 3D',
  description: 'Generated by create next app',
  // icons: ['icon.ico'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} min-h-[125vh] antialiased`}>
        <NextAuthWrapper>
          <CartProvider>{children}</CartProvider>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
